// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiwwoibjneoosemychvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpd3dvaWJqbmVvb3NlbXljaHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDMyNjAsImV4cCI6MjA2OTg3OTI2MH0.vxvEbt7n-y4zeRSEZV8lIN_dgUVd51_4k146eligOLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});